# Generated by Django 4.1.3 on 2023-01-01 19:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(max_length=20, unique=True)),
                ('acitivity_duration', models.CharField(choices=[('1H', '1 hour'), ('2H', '2 hour'), ('3H', '3 hour'), ('1D', '1 Day'), ('2D', '2 Day'), ('4D', '4 Day'), ('6D', '6 Day')], max_length=2)),
                ('description', models.CharField(max_length=250)),
                ('net_cost', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)])),
                ('activity_status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['activity_title'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(help_text='<em>10 digits</em>', max_length=12, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('pax', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Phone'), ('founder', 'Founder'), ('socialm', 'Social Media'), ('web', 'Website'), ('other', 'Other')], max_length=10)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=25, unique=True)),
                ('customer_rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('room_category', models.CharField(max_length=15)),
                ('net_cp', models.PositiveIntegerField(default=0, help_text='Per Day for 2pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='CP')),
                ('net_map', models.PositiveIntegerField(default=0, help_text='Per Day for 2pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='MAP')),
                ('net_cp_kid', models.PositiveIntegerField(default=0, help_text='Per Day for 1pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='CP Kid')),
                ('net_map_kid', models.PositiveIntegerField(default=0, help_text='Per Day for 1pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='MAP Kid')),
            ],
            options={
                'ordering': ['customer_rating'],
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_last_updated', models.DateTimeField(auto_now=True)),
                ('entry_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.CharField(blank=True, choices=[('Enquiry', 'Enquiry'), ('Proposal', 'Proposal'), ('Confirmed', 'Confirmed'), ('Passed', 'Passed'), ('VIP', 'VIP'), ('Defense', 'Defense'), ('F-n-F', 'F-n-F')], max_length=11, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='yyyy-mm-dd,hh--mm')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pb_rooms', models.PositiveSmallIntegerField(default=0, help_text='Number of Rooms', verbose_name='PB Rooms')),
                ('pb_nights', models.PositiveSmallIntegerField(default=0, help_text='include return nights', verbose_name='PB Nights')),
                ('hv_rooms', models.PositiveSmallIntegerField(default=0, help_text='Number of Rooms', verbose_name='HV Rooms')),
                ('hv_nights', models.PositiveSmallIntegerField(default=0, verbose_name='HV Nights')),
                ('nl_rooms', models.PositiveSmallIntegerField(default=0, help_text='Number of Rooms', verbose_name='NL Rooms')),
                ('nl_nights', models.PositiveSmallIntegerField(default=0, verbose_name='NL Nights')),
                ('duration', models.PositiveSmallIntegerField(blank=True, verbose_name='Trip Nights')),
                ('trip_completed', models.BooleanField(default=False)),
                ('transfers', models.CharField(blank=True, choices=[('PB-HV-PB-ALL', 'PB-HV AI'), ('PB-HV-NL-PB-ALL', 'PB-HV-NL AI'), ('PB-HV-PB-PnD', 'PB-HV P-n-D'), ('PB-HV-NL-PB-PnD', 'PB-HV-NL P-n-D'), ('PB-HV-Ferry', 'Ferry-Only-PB-HV'), ('PB-HV-NL-Ferry', 'Ferry-Only-PB-HV-NL')], max_length=21, null=True)),
                ('transfer_cost', models.PositiveIntegerField(blank=True, default=0)),
                ('hotel_cost', models.PositiveIntegerField(default=0)),
                ('advance_paid', models.PositiveIntegerField(default=0)),
                ('activity_cost', models.PositiveIntegerField(default=0)),
                ('total_trip_cost', models.PositiveIntegerField(default=0)),
                ('activities', models.ManyToManyField(blank=True, help_text='select multiple, note locations', related_name='activities', to='gobasic.activity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gobasic.customer')),
                ('hotel_hv', models.ForeignKey(blank=True, limit_choices_to={'location': 'Havelock Island'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hv_hotel_set', to='gobasic.hotel', verbose_name='Hotel HV')),
                ('hotel_nl', models.ForeignKey(blank=True, limit_choices_to={'location': 'Niel Island'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nl_hotel_set', to='gobasic.hotel', verbose_name='Hotel NL')),
                ('hotel_pb', models.ForeignKey(blank=True, limit_choices_to={'location': 'Port Blair'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pb_hotel_set', to='gobasic.hotel', verbose_name='Hotel PB')),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gobasic.timestamps')),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gobasic.locations'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gobasic.timestamps'),
        ),
        migrations.AddField(
            model_name='customer',
            name='timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gobasic.timestamps'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gobasic.locations'),
        ),
        migrations.AddField(
            model_name='activity',
            name='timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gobasic.timestamps'),
        ),
    ]
