# Generated by Django 4.1.3 on 2023-02-05 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='description',
            new_name='Inclusions',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='customer_transfer',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gobasic.customer', verbose_name='Customer->Transfer'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_title',
            field=models.CharField(choices=[('All', 'All Inclusive'), ('Part', 'Partial'), ('Frac', 'Fractional')], max_length=20, unique=True, verbose_name='Type'),
        ),
    ]
