# Generated by Django 4.1.3 on 2022-11-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_location',
            field=models.CharField(choices=[('Pb', 'Port Blair'), ('Hv', 'Havelock'), ('Nl', 'Neil')], default='Pb', max_length=2),
        ),
    ]
