# Generated by Django 4.1.3 on 2023-05-16 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gobasic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gobasic.customer'),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_hv',
            field=models.ForeignKey(blank=True, limit_choices_to={'location': 'Havelock Island'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hv_hotel_set', to='gobasic.hotel', verbose_name='Hotel Havelock'),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_nl',
            field=models.ForeignKey(blank=True, limit_choices_to={'location': 'Neil Island'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nl_hotel_set', to='gobasic.hotel', verbose_name='Hotel Neil'),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_pb',
            field=models.ForeignKey(blank=True, limit_choices_to={'location': 'Port Blair'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pb_hotel_set', to='gobasic.hotel', verbose_name='Hotel Port Blair'),
        ),
        migrations.AddField(
            model_name='trip',
            name='transfers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gobasic.transfer'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='customer_transfer',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gobasic.customer', verbose_name='Customer->Transfer'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gobasic.locations'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gobasic.locations'),
        ),
    ]
