# Generated by Django 4.1.3 on 2023-03-02 00:14

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=11, editable=False, populate_from='customer', unique=True),
            preserve_default=False,
        ),
    ]
