# Generated by Django 4.1.3 on 2022-11-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0002_activity_activity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='acitivity_hv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hv_activity_set', to='gobasic.activity'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='acitivity_nl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nl_activity_set', to='gobasic.activity'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='acitivity_pb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pb_activity_set', to='gobasic.activity'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_hv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hv_hotel_set', to='gobasic.hotel'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_nl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nl_hotel_set', to='gobasic.hotel'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_pb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pb_hotel_set', to='gobasic.hotel'),
        ),
    ]
