# Generated by Django 4.1.3 on 2023-01-08 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0002_alter_trip_hotel_hv_alter_trip_hotel_nl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='hotel_hv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hv_hotel_set', to='gobasic.hotel', verbose_name='Hotel HV'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_nl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nl_hotel_set', to='gobasic.hotel', verbose_name='Hotel NL'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_pb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pb_hotel_set', to='gobasic.hotel', verbose_name='Hotel PB'),
        ),
    ]
