# Generated by Django 4.1.3 on 2023-05-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='room_name',
            field=models.CharField(max_length=60),
        ),
    ]
