# Generated by Django 4.1.3 on 2023-01-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0003_alter_trip_hotel_hv_alter_trip_hotel_nl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='room_categories',
            field=models.CharField(choices=[('Budget', 'Budget'), ('Premium', 'Premium'), ('Deluxe', 'Deluxe'), ('Luxury', 'Luxury'), ('Ultra Luxury', 'Ultra Luxury')], default='1', max_length=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_hv',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_id': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hv_hotel_set', to='gobasic.hotel', verbose_name='Hotel HV'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_nl',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_id': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nl_hotel_set', to='gobasic.hotel', verbose_name='Hotel NL'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_pb',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_id': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pb_hotel_set', to='gobasic.hotel', verbose_name='Hotel PB'),
        ),
    ]
