# Generated by Django 4.1.3 on 2023-05-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0003_alter_hotel_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=60),
        ),
    ]
