# Generated by Django 4.1.3 on 2023-03-09 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gobasic', '0004_alter_transfer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
