# Generated by Django 4.1.3 on 2022-11-01 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0004_rename_acitivity_hv_trip_activity_hv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 11, 2)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 2), help_text='yyyy-mm-dd,hh--mm'),
        ),
    ]
