# Generated by Django 4.1.3 on 2023-01-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0004_alter_hotel_room_categories_alter_trip_hotel_hv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=25),
        ),
    ]
