# Generated by Django 4.1.3 on 2023-03-21 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0005_trip_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-entry_last_updated']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-entry_created']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-entry_last_updated']},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-transfer_type']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-entry_created']},
        ),
        migrations.AddField(
            model_name='hotel',
            name='net_ap',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 2pax', validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)], verbose_name='AP'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='net_ap_kid',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 1pax', validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)], verbose_name='AP Kid'),
        ),
    ]
