# Generated by Django 4.1.3 on 2023-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0005_alter_hotel_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='plan_hv',
            field=models.CharField(choices=[('net_cp', 'Breakfast'), ('net_map', 'Breakfast + 1 Meal'), ('net_cp_kid', 'Child Breakfast'), ('net_map_kid', 'Child Breakfast + 1 Meal')], default='CP', max_length=11),
        ),
        migrations.AddField(
            model_name='trip',
            name='plan_nl',
            field=models.CharField(choices=[('net_cp', 'Breakfast'), ('net_map', 'Breakfast + 1 Meal'), ('net_cp_kid', 'Child Breakfast'), ('net_map_kid', 'Child Breakfast + 1 Meal')], default='CP', max_length=11),
        ),
        migrations.AddField(
            model_name='trip',
            name='plan_pb',
            field=models.CharField(choices=[('net_cp', 'Breakfast'), ('net_map', 'Breakfast + 1 Meal'), ('net_cp_kid', 'Child Breakfast'), ('net_map_kid', 'Child Breakfast + 1 Meal')], default='CP', max_length=11),
        ),
    ]
