# Generated by Django 4.1.3 on 2023-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0006_alter_activity_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
