# Generated by Django 4.1.3 on 2023-01-10 19:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0006_trip_plan_hv_trip_plan_nl_trip_plan_pb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='net_cp',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 2pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='CP'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='net_cp_kid',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 1pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='CP Kid'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='net_map',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 2pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='MAP'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='net_map_kid',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 1pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='MAP Kid'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_hv',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_id': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hv_hotel_set', to='gobasic.hotel', verbose_name='Hotel Havelock'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_nl',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_id': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nl_hotel_set', to='gobasic.hotel', verbose_name='Hotel Neil'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_pb',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_id': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pb_hotel_set', to='gobasic.hotel', verbose_name='Hotel Port Blair'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hv_nights',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Havelock Nights'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hv_rooms',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of Rooms', validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)], verbose_name='Havelock Rooms'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='nl_nights',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Neil Nights'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='nl_rooms',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of Rooms', validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)], verbose_name='Neil Rooms'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pb_nights',
            field=models.PositiveSmallIntegerField(default=0, help_text='Port Blair Nights', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Port Blair Nights'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pb_rooms',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of Rooms', validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)], verbose_name='Port Blair Rooms'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='plan_hv',
            field=models.CharField(choices=[('net_cp', 'Breakfast'), ('net_map', 'Breakfast + 1 Meal')], default='CP', max_length=11, verbose_name='Meal Plan'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='plan_nl',
            field=models.CharField(choices=[('net_cp', 'Breakfast'), ('net_map', 'Breakfast + 1 Meal')], default='CP', max_length=11, verbose_name='Meal Plan'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='plan_pb',
            field=models.CharField(choices=[('net_cp', 'Breakfast'), ('net_map', 'Breakfast + 1 Meal')], default='CP', max_length=11, verbose_name='Meal Plan'),
        ),
    ]
