# Generated by Django 4.1.3 on 2022-11-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0007_alter_trip_end_date_alter_trip_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='start_date',
        ),
    ]
