# Generated by Django 4.1.3 on 2022-11-01 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0008_remove_customer_end_date_remove_customer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='ap_child',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ap_cost',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='cp_child',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='cp_cost',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ep_child',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ep_cost',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='map_child',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='map_cost',
        ),
        migrations.AddField(
            model_name='hotel',
            name='ap',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 2pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='AP'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ap_kid',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 1pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='AP Kid'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cp',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 2pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='CP'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cp_kid',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 1pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='CP Kid'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ep',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 2pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='EP'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ep_kid',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 1pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='EP Kid'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='map',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 2pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='MAP'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='map_kid',
            field=models.PositiveIntegerField(default=0, help_text='Per Day for 1pax', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='MAP Kid'),
        ),
    ]
