# Generated by Django 4.1.3 on 2022-11-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0009_remove_hotel_ap_child_remove_hotel_ap_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-margin']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='customer_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(choices=[('Pb', 'Port Blair'), ('Hv', 'Havelock'), ('Nl', 'Neil')], default='Pb', max_length=2),
        ),
    ]
