# Generated by Django 4.1.3 on 2022-11-03 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0010_alter_activity_options_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='activity_hv',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='activity_nl',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='activity_pb',
        ),
        migrations.AddField(
            model_name='trip',
            name='activity',
            field=models.ManyToManyField(to='gobasic.activity'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_hv',
            field=models.ForeignKey(blank=True, limit_choices_to={'location': 'Hv'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hv_hotel_set', to='gobasic.hotel'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_nl',
            field=models.ForeignKey(blank=True, limit_choices_to={'location': 'Nl'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nl_hotel_set', to='gobasic.hotel'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_pb',
            field=models.ForeignKey(blank=True, limit_choices_to={'location': 'Pb'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pb_hotel_set', to='gobasic.hotel'),
        ),
    ]
