# Generated by Django 4.1.3 on 2022-11-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0011_remove_trip_activity_hv_remove_trip_activity_nl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pax',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
