# Generated by Django 4.1.3 on 2022-11-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0012_customer_pax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='ap',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ap_kid',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ep',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ep_kid',
        ),
        migrations.AddField(
            model_name='trip',
            name='hv_nights',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='nl_nights',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='pb_nights',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
