# Generated by Django 4.1.3 on 2022-11-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0013_remove_hotel_ap_remove_hotel_ap_kid_remove_hotel_ep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='hv_nights',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='nl_nights',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pb_nights',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
