# Generated by Django 4.1.3 on 2022-11-04 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0014_alter_trip_hv_nights_alter_trip_nl_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transfers',
            field=models.CharField(blank=True, choices=[('PB-HV-PB', 'Havelock Round Trip'), ('PB-HV-NL-PB', 'Havelock-Neil Round Trip')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activity',
            field=models.ManyToManyField(help_text='select multiple, note location tags', to='gobasic.activity', verbose_name='Activities'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Trip Nights'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_hv',
            field=models.ForeignKey(blank=True, limit_choices_to={'location': 'Hv'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hv_hotel_set', to='gobasic.hotel', verbose_name='Hotel HV'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_nl',
            field=models.ForeignKey(blank=True, limit_choices_to={'location': 'Nl'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nl_hotel_set', to='gobasic.hotel', verbose_name='Hotel NL'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_pb',
            field=models.ForeignKey(blank=True, limit_choices_to={'location': 'Pb'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pb_hotel_set', to='gobasic.hotel', verbose_name='Hotel PB'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hv_nights',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='HV Nights'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='nl_nights',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='NL Nights'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pb_nights',
            field=models.PositiveSmallIntegerField(default=0, help_text='include return nights', verbose_name='PB Nights'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_cost',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
