# Generated by Django 4.1.3 on 2022-11-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0015_trip_transfers_alter_trip_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hv_rooms',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of Rooms', verbose_name='HV Rooms'),
        ),
        migrations.AddField(
            model_name='trip',
            name='nl_rooms',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of Rooms', verbose_name='NL Rooms'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pb_rooms',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of Rooms', verbose_name='PB Rooms'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activity',
            field=models.ManyToManyField(blank=True, help_text='select multiple, note location tags', to='gobasic.activity', verbose_name='Activities'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
