# Generated by Django 4.1.3 on 2022-11-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0016_trip_hv_rooms_trip_nl_rooms_trip_pb_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transfer_cost',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
