# Generated by Django 4.1.3 on 2022-11-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0019_remove_trip_activity_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='balance_due',
            new_name='hotel_cost',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='total_cost',
        ),
    ]
