# Generated by Django 4.1.3 on 2022-11-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0020_rename_balance_due_trip_hotel_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='activity_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activity',
            field=models.ManyToManyField(blank=True, help_text='select multiple, note location tags', related_name='activities', to='gobasic.activity', verbose_name='Activities'),
        ),
    ]
