# Generated by Django 4.1.3 on 2022-11-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0021_trip_activity_cost_alter_trip_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_trip_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
