# Generated by Django 4.1.3 on 2022-11-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobasic', '0022_trip_total_trip_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-entry_created']},
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='cp',
            new_name='net_cp',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='cp_kid',
            new_name='net_cp_kid',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='map',
            new_name='net_map',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='map_kid',
            new_name='net_map_kid',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='mrp_cost',
        ),
    ]
